### ISSUE TITLE
missing file 

### ISSUE THREAD

**Issue by tariqtomar** [Sherrylone/PQDiff#1]
Hello, i am getting problem in running the model as it asks for the missing file at the path "assets/stable-diffusion/autoencoder_kl.pth".

**Comment by Sherrylone** [comment]
Hello, you can download the autoencoder_kl.pth from 
https://drive.google.com/file/d/130Cq8uFKEqK8sgroIwN7hnRdNvB9DkCo/view?usp=sharing

**Comment by tariqtomar** [comment]
thank you so much for quick reply.
