### ISSUE TITLE
Sampling cannot reproduce the result

### ISSUE THREAD

**Issue by HandFi** [Sherrylone/PQDiff#10]
Hi authors, 

Great work!

I did not modify your code and just played with the scenery dataset. The training stages are all fine.
However, when I moved to the sampling stage to see the outputs, it gives me results like this:

![image](https://github.com/Sherrylone/PQDiff/assets/137986298/c180682c-22e9-4f6d-b24c-9b782aab8e5c)
![image](https://github.com/Sherrylone/PQDiff/assets/137986298/c7cd689c-76fc-4765-b078-807b127bd7e3)

Seems like I am not able to get {Outpainting in an arbitrary position}

Could you please comment on that?

Many thanks,
Olivia

**Comment by ucasyjz** [comment]
Do you know the usage of the open-source weights, I meet a problem
