### ISSUE TITLE
Training results

### ISSUE THREAD

**Issue by bhosalems** [Sherrylone/PQDiff#14]
I wanted to reproduce the results on flicker/sceneray dataset. After training 15000 steps i still see results that do not look good, any advice?

![image](https://github.com/user-attachments/assets/36594406-6898-4ad6-835f-4fbb4ebe1cd4)

**Comment by Sherrylone** [comment]
You can increase the number of iterations to 100k.

**Comment by ustczhouyu** [comment]
> I wanted to reproduce the results on flicker/sceneray dataset. After training 15000 steps i still see results that do not look good, any advice?
> 
> ![image](https://private-user-images.githubusercontent.com/10846405/352552052-36594406-6898-4ad6-835f-4fbb4ebe1cd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDIwNDAsIm5iZiI6MTcyNDQwMTc0MCwicGF0aCI6Ii8xMDg0NjQwNS8zNTI1NTIwNTItMzY1OTQ0MDYtNjg5OC00YWQ2LTgzNWYtNGZiYjRlYmUxY2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA4MjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0N2Q1MWI2MGYzNDM0NTRmNDE0NGUwZjQ4ZjliMTI2NDAyMTgzNTM1ODU1NDg2ZDk0YTZkMTcyNzc3NGYzMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0HT4-sHhFl8Q-oNBa1pc4MBMBTq4XSbHb0F9Fp09zM4)

I met the same problem when I sample at 10000 steps, have you solved this problem?

**Comment by mondalanindya** [comment]
Decrease your learning rate, worked for me!
