### ISSUE TITLE
Issues in generating an extended image

### ISSUE THREAD

**Issue by tariqtomar** [Sherrylone/PQDiff#3]
I trained the model with the scenery dataset and when i am trying to generate an extended image it is creating a colorful noisy image. Not able to figure out what actually the issue is. I think there is something wrong in the decoder part. Please find the attached files for the reference.
![ori](https://github.com/Sherrylone/PQDiff/assets/130923342/149c1dc2-452a-4d37-a5f4-a3f5e4591f13)
![gen](https://github.com/Sherrylone/PQDiff/assets/130923342/3d69fa9e-1acf-4063-8374-31612e5e77c0)
![copy](https://github.com/Sherrylone/PQDiff/assets/130923342/a623b707-9a98-431f-b2fc-7181d48b954e)

**Comment by Sherrylone** [comment]
Could you provide the training log?

**Comment by tariqtomar** [comment]
Yeah sure
[output.log](https://github.com/Sherrylone/PQDiff/files/14417039/output.log)

**Comment by Sherrylone** [comment]
Hi, you should train the model with longer iterations, e.g., 100k steps.

**Comment by tariqtomar** [comment]
This are the training samples results. 
**Prime anchor**
![prime_anchor-1601](https://github.com/Sherrylone/PQDiff/assets/130923342/4ce839cb-2b53-4f4e-9860-210a54155513)

**decode anchor**
![decode_anchor-1601](https://github.com/Sherrylone/PQDiff/assets/130923342/46d81a48-fd5d-426d-8845-29b04d661212)

**prime target**
![prime_target-1601](https://github.com/Sherrylone/PQDiff/assets/130923342/27e7d278-13e9-4f51-9ba3-57e8a18d51b8)

**decode target**
![decode_target-1601](https://github.com/Sherrylone/PQDiff/assets/130923342/52a28ca5-9833-4fd5-a04a-a78bfb77695c)

**predict target**
![predict_target-1601](https://github.com/Sherrylone/PQDiff/assets/130923342/31755d0d-f42a-4110-986b-969d67cf522a)

**Comment by tariqtomar** [comment]
actually i am testing with my custom dataset and I have only 150 samples to train, for that i have trained the model with 2000 steps and got similar results.

**Comment by Sherrylone** [comment]
Hi, although there are only 150 samples, I think 2000 steps are not enough to converge. 

Therefore, perhaps you can change the model to a smaller size, and reduce the steps to 30k?

**Comment by tariqtomar** [comment]
Thanks for the reply. It worked with higher number of steps and by increasing some more samples.

**Comment by ucasyjz** [comment]
> Thanks for the reply. It worked with higher number of steps and by increasing some more samples.

Can you give me the trained weight on Scenery, thank you
