### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by yxWu777** [Sherrylone/PQDiff#9]
Hello, according to the UViT network in the code, if the image size during training and output can only be the shape of (192，192)? But in the article, I remembered that we can denote a (w, h) as the predefined resolution to be generated. Can this be achieved without adjusting the network structure? Thank you so much for your reply.

**Comment by Sherrylone** [comment]
Thanks for your interest. Currently, PQDiff only supports fixed-resolution outpainting.

**Comment by yxWu777** [comment]
Thank you so much.
